### ISSUE TITLE
Rukus Unleashed Backup

### ISSUE THREAD

**Issue by vignesh8458** [ms264556/aioruckus#8]
Hello,

As per your instruction, I run the code with my credentials, I am getting this error, pls help me to resolve the issue.

**Error:**
= RESTART: C:/Users/Administrator.AD/Documents/Python/ruckus.oy.py
Traceback (most recent call last):
  File "C:/Users/Administrator.AD/Documents/Python/ruckus.oy.py", line 17, in <module>
    asyncio.run(backup_demo())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
  File "C:/Users/Administrator.AD/Documents/Python/ruckus.oy.py", line 13, in backup_demo
    backup = await session.api.get_backup()
AttributeError: 'RuckusAjaxApi' object has no attribute 'get_backup'

_____________________________________________________________________________________________________________________________

**Code:**

 import asyncio
from datetime import datetime
from aioruckus import AjaxSession

async def backup_demo():
    """aioruckus backup demo"""

    backup_filename = "C:\Switch_Backup\Ruckus" + datetime.now().strftime("%y%m%d_%H%M") + ".bak"

    # example of saving a backup
    async with AjaxSession.async_create("<ruckus_ip>", "admin", "<password>") as session:
        backup = await session.api.get_backup()
        with open(backup_filename , "wb") as file:
            file.write(backup)
        
asyncio.run(backup_demo())

**Comment by ms264556** [comment]
Please make sure you grabbed the latest version. I only added get_backup in v0.37

**Comment by vignesh8458** [comment]
Thanks for the update.

It's working now. again thank you for the code.
